site_name: basic tool
nav: 
    - "mkdocs": mkdocs.md
    - "git": git.md
    - "markdown": markdown.md
    - "vscode": vscode.md
    - "python": python.md
    - "index": index.md
#theme: readthedocs
theme:
    name: 'material'