site_name: basic
nav: 
    - "mkdocs": mkdocs.md
    - "git": git.md
    - "markdown": markdown.md
    - "vscode": vscode.md
    - "python": python.md
    - "index": index.md
    - "datastructure": datastructure.md
theme: readthedocs
#theme:
#    name: 'material'